accent = "#f92d0b"
cursor = "#e6d2cf"
foreground = "#e6d2cf"
background = "#160305"
panel_background = "#280b10"
selection_foreground = "#fb1d06"
selection_background = "#49160d"

color0 = "#2c1a17"
color1 = "#f49384"
color2 = "#ee996a"
color3 = "#f3909a"
color4 = "#e6a05a"
color5 = "#ef90af"
color6 = "#f29677"
color7 = "#d3bfbc"
color8 = "#412d2a"
color9 = "#ffb6a9"
color10 = "#ffb891"
color11 = "#ffb3b9"
color12 = "#ffba78"
color13 = "#ffb1c9"
color14 = "#ffb79f"
color15 = "#edd9d6"
